In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('lifestyle weight tracker.csv')

In [29]:
df.head(10)

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
0,275,23,Female,169.355325,111.485330,10,7.016453,211.426469,2801.764291,175.1,315.2,93.4,8172,Strength,6,18.823955,0.317158,111.802488
1,296,43,Female,174.424939,109.699334,1,7.320227,211.979739,2666.001616,166.6,299.9,88.9,7988,NaN,0,36.987432,0.211877,109.911211
2,125,47,Male,163.246320,110.960286,3,7.238641,160.400067,1707.084012,106.7,192.0,56.9,7976,Yoga,10,35.977033,0.122390,111.082676
3,167,42,Female,164.997333,85.546097,7,5.060697,301.629856,2647.458547,165.5,297.8,88.2,8203,Cardio,10,33.141805,0.308449,85.854547
4,311,54,Male,167.696168,135.710505,5,9.866791,335.199126,2036.567163,127.3,229.1,67.9,8024,NaN,0,19.065076,0.120221,135.830726
5,507,49,Female,172.855638,137.710774,9,3.833548,349.804451,2012.347400,125.8,226.4,67.1,8076,NaN,0,37.135372,0.286993,137.997767
6,203,21,Female,174.031122,114.596351,5,8.264721,49.148717,2593.930029,162.1,291.8,86.5,8020,NaN,0,24.305306,0.218840,114.815191
7,448,58,Male,160.356652,128.556222,6,5.430235,189.031759,2193.618345,137.1,246.8,73.1,8083,NaN,0,31.035423,0.219977,128.776199
8,285,38,Female,173.498266,128.647205,7,6.340006,247.988017,1831.201820,114.5,206.0,61.0,8189,NaN,0,23.027797,0.151988,128.799193
9,498,39,Male,162.889462,117.699821,1,4.634465,358.074929,2016.557595,126.0,226.9,67.2,7915,NaN,0,18.913111,0.037771,117.737592

In [30]:
df.columns

Index(['User_ID', 'Age', 'Gender', 'Height_cm', 'Initial_Weight_kg',
       'Stress_Level', 'Sleep_Hours', 'Caffeine_mg', 'Calories_Consumed',
       'Protein_g', 'Carbs_g', 'Fat_g', 'Steps', 'Workout_Type',
       'Workout_Intensity', 'Temp_C', 'Weight_Change', 'Current_Weight_kg'],
      dtype='object')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55000 entries, 0 to 54999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            55000 non-null  int64
 1   Age                55000 non-null  int64
 2   Gender             55000 non-null  object
 3   Height_cm          55000 non-null  float64
 4   Initial_Weight_kg  55000 non-null  float64
 5   Stress_Level       55000 non-null  int64
 6   Sleep_Hours        55000 non-null  float64
 7   Caffeine_mg        55000 non-null  float64
 8   Calories_Consumed  52250 non-null  float64
 9   Protein_g          55000 non-null  float64
 10  Carbs_g            55000 non-null  float64
 11  Fat_g              55000 non-null  float64
 12  Steps              55000 non-null  int64
 13  Workout_Type       27448 non-null  object
 14  Workout_Intensity  55000 non-null  int64
 15  Temp_C             55000 non-null  float64
 16  Weight_Change      55000 non-null  float64
 17  Current_Weight_kg  55000 non-null  float64
dtypes: float64(11), int64(5), object(2)
memory usage: 7.6+ MB

Handling Null values for Calories consumed

In [32]:
df['Calories_Consumed']
df['Calories_Consumed'].isnull()
df['Calories_Consumed'].mean()
df['Calories_Consumed'].fillna(df['Calories_Consumed'].mean()) # did not make changes in table
df['Calories_Consumed']=df['Calories_Consumed'].fillna(df['Calories_Consumed'].mean())

In [33]:
df['Calories_Consumed']
df

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
0,275,23,Female,169.355325,111.485330,10,7.016453,211.426469,2801.764291,175.1,315.2,93.4,8172,Strength,6,18.823955,0.317158,111.802488
1,296,43,Female,174.424939,109.699334,1,7.320227,211.979739,2666.001616,166.6,299.9,88.9,7988,NaN,0,36.987432,0.211877,109.911211
2,125,47,Male,163.246320,110.960286,3,7.238641,160.400067,1707.084012,106.7,192.0,56.9,7976,Yoga,10,35.977033,0.122390,111.082676
3,167,42,Female,164.997333,85.546097,7,5.060697,301.629856,2647.458547,165.5,297.8,88.2,8203,Cardio,10,33.141805,0.308449,85.854547
4,311,54,Male,167.696168,135.710505,5,9.866791,335.199126,2036.567163,127.3,229.1,67.9,8024,NaN,0,19.065076,0.120221,135.830726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54995,288,31,Female,172.989751,130.257318,6,5.791148,271.088251,2268.846150,141.8,255.2,75.6,7935,NaN,0,20.023635,0.175921,151.356362
54996,159,37,Male,179.688824,123.132106,9,7.691768,315.457575,1845.442138,115.3,207.6,61.5,7949,NaN,0,18.972702,0.175562,139.965519
54997,385,19,Female,167.302095,99.227392,3,8.340457,125.622338,2097.729693,150.0,269.9,80.0,7909,NaN,0,16.169056,0.113811,117.888421
54998,570,20,Male,178.401840,106.253039,10,5.833022,386.287965,2407.771582,150.5,270.9,80.3,7897,NaN,0,33.360536,0.340965,128.880845
54999,565,23,Male,175.664016,102.207143,10,10.402248,405.843037,1802.206215,112.6,202.7,60.1,7883,Strength,5,24.044327,0.215855,121.934377

Handle missing value for workout-type

In [34]:
# We will handle none value for workout-type beacause maybe people do not workout
df['Workout_Type']=df['Workout_Type'].fillna('None')
df['Workout_Type']

0        Strength
1            None
2            Yoga
3          Cardio
4            None
           ...
54995        None
54996        None
54997        None
54998        None
54999    Strength
Name: Workout_Type, Length: 55000, dtype: object

Insights for workout_type

In [35]:
df['Workout_Type'].value_counts()

Workout_Type
None        27552
Strength    10976
Cardio      10976
Yoga         5496
Name: count, dtype: int64

Check workout intensity should be zero for none value of workout type

In [36]:
df[df['Workout_Type']=='None']
df[df['Workout_Type']=='None']['Workout_Intensity']
df[df['Workout_Type']=='None']['Workout_Intensity'].sum()

np.int64(0)

In [37]:
# Annothe method --
df['Workout_Type']=='None'
df['Workout_Intensity'] == 0
df[(df['Workout_Type']=='None' )& (df['Workout_Intensity'] == 0)]['Workout_Intensity']

1        0
4        0
5        0
6        0
7        0
        ..
54993    0
54995    0
54996    0
54997    0
54998    0
Name: Workout_Intensity, Length: 27552, dtype: int64

which workout type have max avg intensity

In [ ]:
df.groupby('Workout_Type')['Workout_Intensity'].mean()
max(df.groupby('Workout_Type')['Workout_Intensity'].mean())
df.groupby('Workout_Type')['Workout_Intensity'].mean().sort_values()
df.groupby('Workout_Type')['Workout_Intensity'].mean().sort_values(ascending=False)
df.groupby('Workout_Type')['Workout_Intensity'].mean().sort_values(ascending=False).head(1)

Workout_Type
Yoga    7.0504
Name: Workout_Intensity, dtype: float64

avg weight change of workout type

In [62]:
df.groupby('Workout_Type')['Weight_Change'].mean()
max(df.groupby('Workout_Type')['Weight_Change'].mean())
df.groupby('Workout_Type')['Weight_Change'].mean().sort_values()
df.groupby('Workout_Type')['Weight_Change'].mean().sort_values(ascending=False)

Workout_Type
Strength    0.168950
Yoga        0.168484
None        0.168434
Cardio      0.168017
Name: Weight_Change, dtype: float64

Weight change of a person with max steps

In [45]:
df['Steps'].max()

8365

In [47]:
df[df['Steps']==df['Steps'].max()]['Weight_Change']

54878    0.244578
Name: Weight_Change, dtype: float64

Tell the average heights for every gender

In [38]:
df['Gender'].value_counts()

Gender
Male      26438
Female    26334
Other      2228
Name: count, dtype: int64

In [39]:
df.groupby('Gender')['Height_cm']
df.groupby('Gender')['Height_cm'].mean()

Gender
Female    169.995617
Male      169.913379
Other     170.396730
Name: Height_cm, dtype: float64

data of person with max height

In [43]:
df['Height_cm']==df['Height_cm'].max()
df[df['Height_cm']==df['Height_cm'].max()]

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
2839,118,44,Male,213.837588,120.022851,2,7.557805,194.054919,2123.524437,132.7,238.9,70.8,8041,Strength,5,25.846116,0.105277,120.359498

data of person with min height

In [44]:
df['Height_cm']==df['Height_cm'].min()
df[df['Height_cm']==df['Height_cm'].min()]

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
44968,449,26,Female,126.190233,143.355274,6,6.052643,81.845581,2109.872259,131.9,237.4,70.3,7928,None,0,25.023106,0.180331,157.71593

Tell the average initial weight for every gender

In [63]:
df.groupby('Gender')['Initial_Weight_kg']
df.groupby('Gender')['Initial_Weight_kg'].mean()

Gender
Female    115.022398
Male      114.969810
Other     115.091650
Name: Initial_Weight_kg, dtype: float64

Average weight_change of those whose stres level is max

In [ ]:
df[df['Stress_Level']==df['Stress_Level'].max()]
df[df['Stress_Level']==df['Stress_Level'].max()]['Weight_Change']
df[df['Stress_Level']==df['Stress_Level'].max()]['Weight_Change'].mean()

np.float64(0.2585646620122999)

MAximum calories consumed

In [72]:
df['Calories_Consumed'].max()

4874.404173110623

Person with high calories and low steps

In [69]:
df['Steps']==df['Steps'].min()
(df['Calories_Consumed']==df['Calories_Consumed'].max())
df[(df['Steps']==df['Steps'].min()) & (df['Calories_Consumed']==df['Calories_Consumed'].max())]

Empty DataFrame
Columns: [User_ID, Age, Gender, Height_cm, Initial_Weight_kg, Stress_Level, Sleep_Hours, Caffeine_mg, Calories_Consumed, Protein_g, Carbs_g, Fat_g, Steps, Workout_Type, Workout_Intensity, Temp_C, Weight_Change, Current_Weight_kg]
Index: []